### ISSUE TITLE
[Help wanted] VBoxManage.exe gives error- disabled BIOS

### ISSUE THREAD

**Issue by sharma-samta** [sinajahan/testing-microservices-workshop#1]
Hi there,

I installed the tools and then while setting up the vm , i encountered this error: 

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "cea2c00f-d6d0-45f6-9368-94ba8acc9557", "--type", "headless
"]

Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (V
ERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,

I tried enabling the BIOS in HP laptop but i cant enable it as it seems to be protected by Corporate Security. 

May I know if there is an alternate to this or a workaround? I have a linux vm also but not sure what all your environment requirements are. 

Thanks

**Comment by sinajahan** [comment]
Hi @sharma-samta. Thanks for reaching out. If your BIOS is locked you can not run these on virtual box. However you can just try to run them on your own machine. Our goal with virtual box and Vagrant was to avoid polluting your machine with node and docker, but if virtual box is not an option for you please try to install node and npm on your machine directly: https://nodejs.org/en/ and also https://www.docker.com/.

**Comment by sinajahan** [comment]
In order to test if your machine is setup correctly try to run these commands and see if you see the desired output:

**Comment by sinajahan** [comment]
In order to test if your machine is setup correctly try to run these commands and see if you see the desired output:

**Comment by sinajahan** [comment]
In order to test if your machine is setup correctly try to run these commands and see if you see the desired output:

```
➜  cd testing-microservices-workshop/topics/finish/01-getting-started/shop
➜  shop git:(master) npm test
```

And you should see something similar to:

```

> shop@0.0.0 test /Users/sjahan/dev/testing-microservices-workshop/topics/finish/01-getting-started/shop
> mocha test.js



  shop
    ✓ returns sorted products alphabetically (1353ms)


  1 passing (1s)
```

**Comment by sinajahan** [comment]
@sharma-samta can you please try to do the above and let us know if that works for you?

**Comment by sharma-samta** [comment]
Thanks @sinajahan. It worked for me.
