### ISSUE TITLE
testing-microservices-workshop

### ISSUE THREAD

**Issue by Groverpooja** [sinajahan/testing-microservices-workshop#2]
Hi , 

I am getting permission denied message  

pogrover@BMOTEC6069397LT MINGW32 ~
$ git clone git@github.com:sinajahan/testing-microservices-workshop.git
Cloning into 'testing-microservices-workshop'...
WARNING
THE PROGRAMS AND DATA STORED ON THIS SYSTEM ARE
LICENSED TO OR ARE PRIVATE PROPERTY OF THIS COMPANY
AND ARE LAWFULLY AVAILABLE ONLY TO AUTHORIZED USERS
FOR APPROVED PURPOSES.  UNAUTHORIZED ACCESS TO ANY
PROGRAM OR DATA ON THIS SYSTEM IS NOT PERMITTTED, AND
ANY UNAUTHORIZED ACCESS BEYOND THIS POINT MAY LEAD
TO PROSECUTION.  THIS SYSTEM MAY BE MONITORED AT ANY
TIME FOR OPERATIONAL REASONS, THEREFORE, IF YOU ARE
NOT AN AUTHORIZED USER, DO NOT ATTEMPT TO LOG ON.
AVERTISSEMENT
LES PROGRAMMES ET LES DONNEES STOCKES DANS CE
SYSTEME SONT VISES PAR UNE LICENCE OU SONT PROPRIETE
PRIVEE DE CETTE COMPAGNIE ET ILS NE SONT ACCESSIBLES
LEGALEMENT QU'AUX USAGERS AUTORISES A DES FINS AUTORISEES.
IL EST INTERDIT D'Y ACCEDER SANS AUTORISATION, ET TOUT
ACCES NON AUTORISE AU DELA DE CE POINT PEUT ENTRAINER DES
POURSUITES. LE SYSTEME PEUT EN TOUT TEMPS FAIRE L'OBJET
D'UNE SURVEILLANCE. SI VOUS N'ETES PAS UN USAGER
AUTORISE, N'ESSAYEZ PAS D'Y ACCEDER.

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by sinajahan** [comment]
Hi @Groverpooja, Looks like your computer is locked under corporate security. For the purpose of this workshop you can just download the content as zip. Here is a screen shot of how to do so:

![image](https://user-images.githubusercontent.com/1117646/36113125-d07f716e-0ff9-11e8-8c54-ea26ff62a23f.png)

Can you please test and let us know if you can get to the next step?

**Comment by Groverpooja** [comment]
HI , 

Thanks for the reply , and I am able to download the content to my PC. 

Thanks 
Pooja
